//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public Dish()
        {
            this.SubOrder = new HashSet<SubOrder>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> PromotionalPrice { get; set; }
        public string PicPath { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<bool> IsServed { get; set; }
        public Nullable<int> MenuID { get; set; }
    
        public virtual ICollection<SubOrder> SubOrder { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
