//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Dish = new HashSet<Dish>();
        }
    
        public int ID { get; set; }
        public string Category { get; set; }
        public string Subcategory { get; set; }
    
        public virtual ICollection<Dish> Dish { get; set; }
    }
}
