//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.SubOrder = new HashSet<SubOrder>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public int TableID { get; set; }
        public Nullable<int> WaiterID { get; set; }
        public string Comment { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int State { get; set; }
    
        public virtual Table Table { get; set; }
        public virtual User User { get; set; }
        public virtual Waiter Waiter { get; set; }
        public virtual ICollection<SubOrder> SubOrder { get; set; }
    }
}
