//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int DishID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual User User { get; set; }
        public virtual SubOrder SubOrder { get; set; }
    }
}
