//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.Order = new HashSet<Order>();
            this.Reservation_List = new HashSet<Reservation_List>();
        }
    
        public int ID { get; set; }
        public string Comment { get; set; }
        public int Capacity { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Reservation_List> Reservation_List { get; set; }
    }
}
