//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Order = new HashSet<Order>();
            this.Reservation_List = new HashSet<Reservation_List>();
            this.DishRatings = new HashSet<DishRatings>();
        }
    
        public int ID { get; set; }
        public string City { get; set; }
        public string Comment { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> Reputation { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Reservation_List> Reservation_List { get; set; }
        public virtual ICollection<DishRatings> DishRatings { get; set; }
    }
}
